### ISSUE TITLE
not compatible with emacs-master

### ISSUE THREAD

**Issue by Dickby** [stardiviner/eldoc-overlay-mode#1]
Since this package requires inline-docs-1.0.1, which is not available for emacs 26.05, eldoc-overlay-mode is not compatible with the actual master-branch

**Comment by NateEag** [comment]
I encountered the same issue on Emacs 25.1 - package.el lists the latest version of this library as 'incompatible'.

**Comment by jmfirth** [comment]
Just encountered

**Comment by stardiviner** [comment]
Does `inline-docs` still not available for `Emacs 26.05` now? If yes, is that because of some changes in `Emacs 26.05` that I don't know?

**Comment by stardiviner** [comment]
Close for now, it someone got this problem still, please open this issue.
