### ISSUE TITLE
Support 24.x

### ISSUE THREAD

**Issue by seagle0128** [stardiviner/eldoc-overlay-mode#2]
Good work! But I don't understand why the `eldoc-overlay-mode` package requires` Emacs 25.1`. I see `inline-docs` package supports `>=24.3`.

Is it able to support `24.x`? Is there any specific reason? Thanks!

**Comment by stardiviner** [comment]
@seagle0128 
Thanks, I updated emacs version requirements. Check it out after MELPA update.
